spring:
  application:
    name: blog

  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  access-time: 3600000
  refresh-time: 2592000000
  prefix: Bearer
  header: Authorization
  secret-key: ${JWT.SECRET}